name: Sync to Google Drive

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Python and pip
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip

    - name: Install dependencies
      run: |
        pip3 install -r requirements-dev.txt

    - name: Install rclone
      run: |
        sudo apt-get install -y rclone

    - name: Set up rclone config and service account key
      run: |
        mkdir -p ~/.config/rclone
        echo "${{ secrets.GDRIVE_CREDS_JSON }}" > gdrive-creds.json
        sed \
          -e "s|{{SERVICE_ACCOUNT_FILE}}|$PWD/gdrive-creds.json|g" \
          -e "s|{{ROOT_FOLDER_ID}}|raspberry_jupiter|g" \
          rclone.conf.template > ~/.config/rclone/rclone.conf

    - name: Sync repository to Google Drive
      run: |
        rclone sync ./ gdrive: \
          --exclude ".git/**" \
          --drive-acknowledge-abuse \
          --quiet
